model: hilcodec
model_kwargs:
    channels_enc: 64
    channels_dec: 96
    n_fft_base: 64
    n_residual_enc: 2
    n_residual_dec: 3
    res_scale_enc: 0.5773502691896258
    res_scale_dec: 0.5773502691896258
    strides: [8, 5, 4, 2]
    kernel_size: 5
    last_kernel_size: 5
    residual_kernel_size: 5
    dilation_base: 1
    skip: identity
    final_activation: Tanh
    act_all: False
    encoder_l2norm: True
    spec: stft
    spec_layer: 1x1_zero
    spec_compression: log
    spec_learnable: False
    pad_mode: constant
    causal: True

    vq_kwargs:
        dim: 128
        codebook_size: 1024     # 16kHz 기준, 1개당 0.5kbps
        num_quantizers: 12
        kmeans_init: True
        decay: 0.99
        ema_num_threshold: 0.5
        ema_num_initial: 0.5
        dropout: True
        dropout_index: [2, 4, 8, 12]  # 1.5, 3, 6, 9 kbps
disc_kwargs:
    mfbd_kwargs:
        use: True
        channels: [32, 128, 512, 1024, 1024]
        kernel_sizes: [5, 5, 5, 5, 5]
        strides: [3, 3, 3, 3, 1]
    mpd_kwargs:
        use: False
    msd_kwargs:
        use: False
    mstftd_kwargs:
        use: True
        magnitude: False
        log_magnitude: True
        eps: 5.0e-2
        n_ffts: [128, 256, 512, 1024]
        hop_lengths: [32, 64, 128, 256]
        win_lengths: [128, 256, 512, 1024]
        filters: 16
        filters_scale: 2
data:
    dataset: 
        train: DirectoriesDataset
        valid: Dataset
        infer: Dataset
        pesq: Dataset
    classes:
        clean:
            directories_to_include:
                - "/home/shahn/Datasets/DNS-Challenge4/datasets_24khz/clean"
                - "/home/shahn/Datasets/VCTK-0.92/wav24_silence_trimmed"
            directories_to_exclude:
                - "/home/shahn/Datasets/VCTK-0.92/wav24_silence_trimmed/p225"
                - "/home/shahn/Datasets/VCTK-0.92/wav24_silence_trimmed/p226"
                - "/home/shahn/Datasets/VCTK-0.92/wav24_silence_trimmed/p227"
                - "/home/shahn/Datasets/VCTK-0.92/wav24_silence_trimmed/p228"
            extension: ".wav"
            probability: 1.0
    transforms:
        RandomGain:
            low_db: -10
            high_db: 6
    length: 150000
    wav_dir: "/home/shahn/Datasets"
    data_dir: ""
    extension: ""
    num_infer: 6
    filelists:
        valid: "filelists/VCTK_valid_24khz.txt"
        infer: "filelists/infer_speech.txt"
        pesq: "filelists/pesq_24khz.txt"
    filter:
        train: False
        valid: False
        pesq: True
    segment_size: 24000
    sampling_rate: 24000
    normalize_method: "random_gain"
    random_gain_low: 0.316      # -10 dB
    random_gain_high: 2.0       # +6 dB
    channels: 1
    n_fft: 1024
    hop_size: 256
    win_size: 1024
    clip_val: 1.0e-5
train:
    disc_lr_ratio: null
    batch_size: 24
    max_epochs: 150
    fp16_g: True
    fp16_d: True
    num_workers: 4
    persistent_workers: True
    clip_grad: null
    seed: 1
    plot_param_and_grad: True
    save_interval: 1
    lookahead: 0
    infer_n: 4     # 'n' of ResidualVQ for infer & pesq. 4 = 3kbps
    
    n_mels_max: 128
    no_zero_at_mel_filter: True
    use_lsgan: False
    use_normalized_fm_loss: True

    balancer_kwargs:
        weights:
            ### 0.9:4:4 ###
            freq: 0.48
            mfbd_g: 1.1
            mfbd_fm: 1.1
            mstftd_g: 1.1
            mstftd_fm: 1.1
        weight_others: 0.01
        ema_decay: 0.99

    optimizer: "AdamP"
    optimizer_kwargs:
        lr: 5.0e-4
        betas: [0.5, 0.9]
        weight_decay: 1.0e-5
    scheduler: CosineAnnealingWarmup
    scheduler_kwargs:
        warmup_iterations: 5000
        eta_min: 1.0e-6
        warn: False
valid:
    batch_size: 48
infer:
    interval: 15
    batch_size: 1
pesq:
    interval: 1000
    batch_size: 12
    num_workers: 0
    num_workers_executor: 32    # num_workers for a multiprocess executor
    metrics_to_calculate:
        pesq: True
        stoi: True
        visqol: True
        visqol_audio: False